services:
  web:
    container_name: csv
    build: .
    volumes:
      - .:/src:rw
    ports:
      - "8001:8001" 
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${MYUSER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

    


  redis:
    container_name: redis_
    image: redis:alpine
    ports:
      - "6380:6379"

  worker:
    container_name: worker
    build: .
    command: celery -A user_data_validator worker --loglevel=info
    volumes:
      - .:/src
    depends_on:
      - redis

volumes:
  postgres_data:
